name: Python application

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  build:
    name: Python Build
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'trigger_pipeline'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: |
          git submodule update --init --recursive
          sudo apt-get update
          sudo apt install exiftool python3-setuptools
          uv sync --all-extras --prerelease=allow --frozen

      - name: Test with unittest
        run: uv run --frozen python -m unittest discover tests
