name: Python application

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  build:
    name: Python Build
    if: github.event_name == 'workflow_dispatch' || github.event.label.name == 'trigger_pipeline'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Clone Flir extractor
        run: |
          git clone https://github.com/ITVRoC/FlirImageExtractor.git --depth 1
          sudo apt install exiftool python-setuptools
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics --exclude FlirImageExtractor/
      - run: pip install -e .
      - name: Test with unittest
        run: |
          python -m unittest discover tests
